### ISSUE TITLE
list.h missing stdint.h

### ISSUE THREAD

**Issue by harlandski** [maurymarkowitz/RetroFOCAL#1]
When running make on my Linux Mint box, I got:

`In file included from src/stdhdr.h:53,
                 from src/retrofocal.h:30,
                 from src/retrofocal.c:29:
src/retrofocal.c: In function ‘variable_value’:
src/list.h:100:48: error: expected ‘)’ before ‘ptr_t’
  100 | #define INT_TO_POINTER(value)     ((void*)(int ptr_t)(value))
      |                                           ~    ^~~~~
src/retrofocal.c:135:50: note: in expansion of macro ‘INT_TO_POINTER’
  135 |    storage->actual_dimensions = lst_append(NULL, INT_TO_POINTER(slots));;
      |                                                  ^~~~~~~~~~~~~~
src/list.h:100:36: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  100 | #define INT_TO_POINTER(value)     ((void*)(int ptr_t)(value))
      |                                    ^
src/retrofocal.c:135:50: note: in expansion of macro ‘INT_TO_POINTER’
  135 |    storage->actual_dimensions = lst_append(NULL, INT_TO_POINTER(slots));;
      |                                                  ^~~~~~~~~~~~~~
make: *** [makefile:22: retrofocal] Error 1
`

I fixed this by adding:

`#include "stdint.h"`

to /src/list.h

After making this change, make ran without error, and the binary retrofocal was created.

**Comment by maurymarkowitz** [comment]
Thanks for the report! I’ve added that import, and pushed a new release with some additional (minor) fixes.

**Comment by harlandski** [comment]
Thanks for the great project, it's a lot of fun to have FOCAL on my laptop and my phone (via Termux) now!
